---
book_repo: docs-book
layout_repo: docs-layout

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true
public_host: docs.pivotal.io
pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 1.3
  changelog_href: https://docs.vmware.com/en/Scheduler-for-VMware-Tanzu/1.3/scheduler-vmware-tanzu/GUID-release-notes.html
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
  use_local_header: true
  latest_stable_version: 1.4
  local_header_img: /images/cloud_rings.png
  local_header_title: Scheduler
  search_placeholder: Search Scheduler 1.3
  url_prefix: scheduler/1-3
  local_product_version: 1.3
  local_header_links: []
  local_header_version_list:
    - <a href="https://docs.pivotal.io/scheduler/1-4/index.html">v1.3</a>
    - <a href="https://docs.pivotal.io/scheduler/1-2/index.html">v1.2</a>
    - <a href="https://resources.docs.pivotal.io/pdfs/scheduler-1.1.pdf">v1.1</a>
    - <a href="https://resources.docs.pivotal.io/pdfs/scheduler-1.0.pdf">v1.0</a>


sections:
  - repository:
      name: docs-content
    directory: scheduler/1-3
    subnav_template: pcf-scheduler_subnav.erb

template_variables:                             # optional

book_title: Pivotal Scheduler
book_repo: docs-book
layout_repo: docs-layout

